[versions]
agp =   "8.5.2"
material = "1.12.0"
appcompat = "1.7.0"
godot = "4.3.0.stable"
playServicesCodeScanner = "16.1.0"
playServicesBase = "18.5.0"

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
godot = { module = "org.godotengine:godot", version.ref = "godot" }
play-services-code-scanner = { module = "com.google.android.gms:play-services-code-scanner", version.ref = "playServicesCodeScanner" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }

